// AUTO-GENERATED by scripts/extract-codex.mjs from the read-only
// guilds codex source page. Structured data for the dedicated codex page.
/* eslint-disable */

export interface CodexMeta { label: string; value: string }
export interface CodexNote { title: string; text: string }
export interface CodexTable { headers: string[]; rows: string[][] }
export interface CodexEntry {
  id: string;
  name: string;
  abbr: string;
  kind: string;
  group: string;
  sub: string;
  intro: string;
  meta: CodexMeta[];
  media: string;
  chips: string[];
  notes: CodexNote[];
  tables: CodexTable[];
}
export interface CodexGroup { name: string; items: string[] }

export const CODEX_GROUPS: CodexGroup[] = [
  {
    "name": "",
    "items": [
      "overview"
    ]
  },
  {
    "name": "Core",
    "items": [
      "nodes",
      "islands"
    ]
  },
  {
    "name": "Combat",
    "items": [
      "siege"
    ]
  }
];

export const CODEX_ENTRIES: Record<string, CodexEntry> = {
  "overview": {
    "id": "overview",
    "name": "Guild Overview",
    "abbr": "OVR",
    "kind": "Shared progression flow",
    "group": "",
    "sub": "Guild progression path",
    "intro": "Guilds are the shared progression layer for organized players. Use Nodes for permanent damage, Guild Islands for your base and facilities, and Guild Siege for contested guild-wide bonuses.",
    "meta": [],
    "media": "Guild system overview",
    "chips": [],
    "notes": [
      {
        "title": "Join or Create",
        "text": "Guild systems require organized players working together."
      },
      {
        "title": "Capture Nodes",
        "text": "Use nodes for permanent damage growth."
      },
      {
        "title": "Build an Island",
        "text": "Send expeditions, claim an island, then develop plots and buildings."
      },
      {
        "title": "Contest Siege",
        "text": "Build the Siege plot and fight over statues for guild-wide bonuses."
      }
    ],
    "tables": []
  },
  "nodes": {
    "id": "nodes",
    "name": "Nodes",
    "abbr": "NODE",
    "kind": "Permanent guild power route",
    "group": "Core",
    "sub": "108 total nodes, 25 energy each",
    "intro": "There are nodes all around Archlight. Capturing a node increases your damage by 0.10%, costs 25 energy, and the source guide lists 108 total nodes for a total of 10.8% damage.",
    "meta": [
      {
        "label": "Damage per node",
        "value": "0.10%"
      },
      {
        "label": "Energy cost",
        "value": "25 energy"
      },
      {
        "label": "Total nodes",
        "value": "108"
      },
      {
        "label": "Total damage",
        "value": "10.8%"
      }
    ],
    "media": "Guild node map or capture example",
    "chips": [
      "Basilisk Side Quest 1",
      "Behemoth Daily Skill Quest 2",
      "Annihilator 1",
      "Banshee Daily Skill Quest 2",
      "Warlords Quest 3",
      "Demon Helmet Quest 1",
      "Seven Trials Quest 2",
      "Voodoo Quest 2",
      "Heroes Quest 4",
      "Elemental Tomb 2",
      "Sharptooth 2",
      "Darksteel Quest 2",
      "Pits of Archlight 2",
      "Iceforged Quest 2",
      "Jorrus Quest 2"
    ],
    "notes": [],
    "tables": [
      {
        "headers": [
          "Where",
          "How many"
        ],
        "rows": [
          [
            "Guild Nodes Level 5",
            "10"
          ],
          [
            "Guild Nodes Level 15",
            "20"
          ],
          [
            "Samurai Nodes",
            "10"
          ],
          [
            "Thurin's Tomb",
            "2"
          ],
          [
            "Forsaken Tomb",
            "2"
          ],
          [
            "The Citadel",
            "1"
          ],
          [
            "Ice Rift",
            "2"
          ],
          [
            "Earth Rift",
            "2"
          ],
          [
            "Fire Rift",
            "2"
          ],
          [
            "Premium Anni",
            "2"
          ]
        ]
      },
      {
        "headers": [
          "Spawn",
          "Nodes"
        ],
        "rows": [
          [
            "Aquatics",
            "4"
          ],
          [
            "Sand Dusk Scarabs",
            "2"
          ],
          [
            "Dragonlings",
            "1"
          ],
          [
            "Grim Reapers",
            "1"
          ],
          [
            "Demons",
            "2"
          ],
          [
            "Enflamed Lords",
            "1"
          ],
          [
            "Corrupted Hydras",
            "2"
          ],
          [
            "Crystal Spiders",
            "2"
          ],
          [
            "Elder Wyrms",
            "1"
          ],
          [
            "Agressive Armadiles",
            "3"
          ],
          [
            "Leviathans",
            "2"
          ],
          [
            "Insectoids",
            "1"
          ],
          [
            "Enraged War Golems",
            "2"
          ],
          [
            "Drakens",
            "1"
          ],
          [
            "Retching Horrors",
            "1"
          ]
        ]
      }
    ]
  },
  "islands": {
    "id": "islands",
    "name": "Guild Islands",
    "abbr": "ISLE",
    "kind": "Base building and guild facilities",
    "group": "Core",
    "sub": "6 island themes, 3 size tiers",
    "intro": "Guild Island replaces the old Guildhall system. Each guild can build a home base with buildings, facilities, plots, and resources that support long-term guild progression.",
    "meta": [],
    "media": "Guild island layout example",
    "chips": [],
    "notes": [],
    "tables": [
      {
        "headers": [
          "Island",
          "Size",
          "Notes"
        ],
        "rows": [
          [
            "Snowland",
            "Small",
            "Small island theme available from the first expedition pool."
          ],
          [
            "Jungle",
            "Small",
            "Same usable area and plot count as other small islands."
          ],
          [
            "Grassfields",
            "Small",
            "Small open field theme with the same small-tier plot structure."
          ],
          [
            "Desert",
            "Medium",
            "Requires owning a small island first."
          ],
          [
            "Undead Swamp",
            "Medium",
            "Same plot count as Desert."
          ],
          [
            "Clouds",
            "Large",
            "Requires owning a medium island and offers the largest plot count."
          ]
        ]
      },
      {
        "headers": [
          "Unlock",
          "Required Guild Island Level"
        ],
        "rows": [
          [
            "Guild Hall Tier 2",
            "Level 3"
          ],
          [
            "Guild Hall Tier 3",
            "Level 5"
          ],
          [
            "Guild Hall Tier 4",
            "Level 7"
          ],
          [
            "Guild Hall Tier 5",
            "Level 10"
          ],
          [
            "Guild Hall Tier 6",
            "Level 15"
          ],
          [
            "Guild Nodes Rooms",
            "Levels 2 and 4"
          ]
        ]
      },
      {
        "headers": [
          "Island Size",
          "6x6 Plots",
          "8x8 Plots",
          "16x16 Plots",
          "32x25 Guild Hall Plot"
        ],
        "rows": [
          [
            "Small",
            "4",
            "6",
            "2",
            "1"
          ],
          [
            "Medium",
            "6",
            "8",
            "3",
            "1"
          ],
          [
            "Big",
            "10",
            "12",
            "5",
            "1"
          ]
        ]
      },
      {
        "headers": [
          "Guild Island Upgrade",
          "Current Value"
        ],
        "rows": [
          [
            "Profession Plot Daily Training Energy",
            "Tier 1: +200 Energy, Tier 2: +300 Energy, Tier 3: +500 Energy"
          ],
          [
            "Blacksmithing Station",
            "Tier 1: 10%, Tier 2: 20%, Tier 3: 30%"
          ],
          [
            "Jewelcrafting Station",
            "Tier 1: 10%, Tier 2: 20%, Tier 3: 30%"
          ],
          [
            "Cooking Station",
            "Tier 1: 10%, Tier 2: 20%, Tier 3: 30%"
          ],
          [
            "Alchemy Station",
            "Tier 1: 10%, Tier 2: 20%, Tier 3: 30%"
          ],
          [
            "Dimensional Studies Cost Pass",
            "Room Creation 5kk gold, build cost 10k Archlight Tokens, Tier 2 20kk gold / 40k tokens, Tier 3 100kk gold / 200k tokens"
          ]
        ]
      }
    ]
  },
  "siege": {
    "id": "siege",
    "name": "Guild Siege",
    "abbr": "SGE",
    "kind": "Contested PvP bonuses",
    "group": "Combat",
    "sub": "13 statues, 12 hour claim lock",
    "intro": "Guild Siege is the contested PvP guild system. After the 5th day from launch, players can enter through the Guild Siege plot inside their Guild Island. Siege access is available all day and is no longer only a Saturday event.",
    "meta": [],
    "media": "Guild siege statue or defense example",
    "chips": [],
    "notes": [],
    "tables": [
      {
        "headers": [
          "Bonus",
          "Effect"
        ],
        "rows": [
          [
            "Siege Token",
            "Every 12 hours, every guild member receives a Siege Token. Two statues have this bonus."
          ],
          [
            "Darkness Shard Chance",
            "+10% chance to drop a Darkness Shard."
          ],
          [
            "Additional Dungeon / Quest Box Chance",
            "+10% chance to receive an extra Dungeon or Quest Box."
          ],
          [
            "Zaqor's Tower Attempts",
            "Every 12 hours, every member receives 2 free attempts at Zaqor's Tower."
          ],
          [
            "Energy Reduction",
            "Reduces energy spent by 10%."
          ],
          [
            "Gathering Profession Experience",
            "+10% Gathering Profession Experience."
          ],
          [
            "Crafting Profession Experience",
            "+10% Crafting Profession Experience."
          ],
          [
            "Experience",
            "+10% Experience."
          ],
          [
            "Monster Essence Chance",
            "+10% Monster Essence Chance."
          ],
          [
            "Loot Chance",
            "+10% Loot Chance."
          ],
          [
            "Gold Drop",
            "+10% Gold Drop."
          ],
          [
            "Reduced Death Penalty",
            "Death Penalty is reduced by 25%."
          ]
        ]
      },
      {
        "headers": [
          "Defense",
          "Description"
        ],
        "rows": [
          [
            "Ballista",
            "Deals base damage every second to enemies within range. Damage and health scale with Siege Plot tier."
          ],
          [
            "Caltrops",
            "Invisible to enemies. Deals true damage based on maximum resources when triggered."
          ],
          [
            "Spike Trap",
            "Invisible to enemies. Deals higher true damage based on maximum resources when triggered."
          ],
          [
            "Fire Trap",
            "Spawns explosive barrels after being triggered. Damage scales with Siege Plot tier."
          ],
          [
            "Ice Trap",
            "Freezes enemies in a small area. Duration scales with Siege Plot tier."
          ],
          [
            "Binding Trap",
            "Prevents movement for a base duration. Duration scales with Siege Plot tier."
          ],
          [
            "Fence",
            "Blocks enemy movement and has health that scales with Siege Plot tier."
          ]
        ]
      },
      {
        "headers": [
          "Spell",
          "Effect"
        ],
        "rows": [
          [
            "Paralyze",
            "Applies paralyze to enemies near the statue."
          ],
          [
            "Reduce Attack Speed",
            "Reduces attack speed of nearby enemies."
          ],
          [
            "Cooldown Increase",
            "Increases cooldowns of nearby enemies."
          ],
          [
            "Reduce Auto Attack Damage",
            "Reduces nearby enemy auto attack damage."
          ]
        ]
      }
    ]
  }
};
