// AUTO-GENERATED by scripts/extract-codex.mjs from the read-only
// professions codex source page. Structured data for the dedicated codex page.
/* eslint-disable */

export interface CodexMeta { label: string; value: string }
export interface CodexNote { title: string; text: string }
export interface CodexTable { headers: string[]; rows: string[][] }
export interface CodexEntry {
  id: string;
  name: string;
  abbr: string;
  kind: string;
  group: string;
  sub: string;
  intro: string;
  meta: CodexMeta[];
  media: string;
  chips: string[];
  notes: CodexNote[];
  tables: CodexTable[];
}
export interface CodexGroup { name: string; items: string[] }

export const CODEX_GROUPS: CodexGroup[] = [
  {
    "name": "",
    "items": [
      "system"
    ]
  },
  {
    "name": "Gathering",
    "items": [
      "farming",
      "fishing",
      "mining",
      "skinning",
      "woodcutting"
    ]
  },
  {
    "name": "Crafting",
    "items": [
      "alchemy",
      "blacksmithing",
      "cooking",
      "jewelcrafting",
      "tanning",
      "woodworking"
    ]
  }
];

export const CODEX_ENTRIES: Record<string, CodexEntry> = {
  "system": {
    "id": "system",
    "name": "Profession System",
    "abbr": "SYS",
    "kind": "Overview and guide flow",
    "group": "",
    "sub": "Core systems, rewards, and energy",
    "intro": "In vast world of Archlight there are many Professions that will help you get your character to the top of the ladder. They can be divided into two categories: Gathering Professions and Crafting Professions. You will get powerful bonuses to you character from Enchancements and Stat Bonuses once you will reach level 50 in each of 6 Crafting Professions. To level them up you will need ALOT of materials so get ready to do some serious gathering sessions (unless of course you're a millionaire, then you can buy all the materials off the market). While rewards from crafting are much more powerful, all professions will grant you lots of Achievement Points that will help you improve your movement speed, loot chance, or even increase experience gained! So in the end spending some time on gathering might be really worthwhile for everyone, to boost ones AP.",
    "meta": [],
    "media": "Profession system overview",
    "chips": [],
    "notes": [],
    "tables": [
      {
        "headers": [
          "Profession Level",
          "Achievement Points"
        ],
        "rows": [
          [
            "5",
            "10",
            "15",
            "20",
            "25",
            "30",
            "35",
            "40",
            "45",
            "50"
          ],
          [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10"
          ]
        ]
      },
      {
        "headers": [
          "Area",
          "Current guide detail"
        ],
        "rows": [
          [
            "Profession window",
            "The profession UI is accessed from the top Character menu and shows profession level progress, current bonuses, station access, material locations, and the tool used for each material."
          ],
          [
            "Stations",
            "Inside a house or Guild Island, the profession window can access stations available in that location. Depot stations only go up to profession level 10."
          ],
          [
            "Tools",
            "Each gathering profession uses an upgradeable tool line. Players progress the tool from Iron through Dragon instead of carrying separate old tool items."
          ],
          [
            "Energy cap",
            "Maximum profession energy is 2,500. Each Prestige level grants +250 maximum energy."
          ],
          [
            "Energy from items",
            "Energy gained from items has a daily limit of +2,000, excluding beds."
          ],
          [
            "Activity energy",
            "Daily tasks grant +25 energy, dungeons grant +100 energy, quests grant +100 energy, and Zaqor’s Tower grants +1,000 energy."
          ],
          [
            "Material assignment",
            "Backpacks can be assigned to profession material categories. Later material assignment support also added an Others section for Slime Materials."
          ],
          [
            "Daily profession tasks",
            "Daily tasks are based on earning profession experience from any source. Completing the daily task grants extra experience and a 10% future craft experience bonus for the day."
          ],
          [
            "Specialization",
            "Crafting professions can specialize after level 50. The specialization level is the level used for Craftsman perk checks."
          ]
        ]
      },
      {
        "headers": [
          "Area",
          "Current guide detail"
        ],
        "rows": [
          [
            "Mining",
            "Celestial Ore Veins and Magic Quartz"
          ],
          [
            "Farming",
            "Saffron"
          ],
          [
            "Fishing",
            "Legendary Fish"
          ],
          [
            "Skinning",
            "Cinnabar Skin Scraps, converted into Cinnabar Leather"
          ],
          [
            "Woodcutting",
            "Enchanted Trees and Enchanted Logs"
          ]
        ]
      }
    ]
  },
  "farming": {
    "id": "farming",
    "name": "Farming",
    "abbr": "FAR",
    "kind": "Gathering Profession",
    "group": "Gathering",
    "sub": "Crop production",
    "intro": "Products from farming are used in Cooking recipes. Cooked meals give significant stat and regen bonuses so it might be worthwhile to get your hands dirty and set up a farm.",
    "meta": [
      {
        "label": "Type",
        "value": "Gathering"
      },
      {
        "label": "Role",
        "value": "Crop production"
      },
      {
        "label": "Energy",
        "value": "10 energy per harvest"
      },
      {
        "label": "Value",
        "value": "Cooking ingredients, daily task progress, Achievement Points, Monster Essence bonus"
      }
    ],
    "media": "Farming plot or crop example",
    "chips": [
      "Overview",
      "How to start",
      "Daily Task",
      "Stat Bonus",
      "Tools"
    ],
    "notes": [
      {
        "title": "Overview",
        "text": "Products from farming are used in Cooking recipes. Cooked meals give significant stat and regen bonuses so it might be worthwhile to get your hands dirty and set up a farm."
      },
      {
        "title": "How to start",
        "text": "1. First of all, you will need a farm. To buy one you have to bid on it just like you bid on Houses . You have to enter house bidding menu and then switch to farms. 2. You get clay watering can from lvl 275 reward."
      },
      {
        "title": "Daily Task",
        "text": "To progress faster you can do daily tasks. Each day you will be asked to harvest specific plants. They will yield 200% of regular experience."
      },
      {
        "title": "Stat Bonus",
        "text": "When you reach certain tresholds with Farming you will get bonus Monster Essence stats. Farming level Bonus 20 +1 40 +2 60 +3 70 +4 80 +5 90 +7 100 +10 110 +15 120 +25 This bonus isn't additive so on level 120 you will have +25 Monster Essence ."
      },
      {
        "title": "Tools",
        "text": "Name Required farming Ingredients Plants you can water Clay Watering Can 0 Seed Merchant 1000 Gold Coins reward (275 lvl) Potatoes Iron Watering Can 10 100 Iron Ingot 5 Crystal Coins 1 Archlight Token Blacksmith Skill (10) Corn Copper Watering Can 20 100 Copper Ingot 25 Crystal C..."
      }
    ],
    "tables": [
      {
        "headers": [
          "Area",
          "Current guide detail"
        ],
        "rows": [
          [
            "Role",
            "Farming supplies vegetables and plants used by crafting, especially Cooking."
          ],
          [
            "Open-world materials",
            "Farming materials can be found in the open world."
          ],
          [
            "Rare material",
            "Harvesting farming materials has a rare chance to drop Saffron."
          ],
          [
            "Advanced cooking",
            "Saffron is used in more advanced Cooking crafts."
          ],
          [
            "Farm upgrades",
            "Farms have four tiers. Upgrades are started from the Profession UI while inside the farm and cost Gold plus Archlight Tokens based on tier."
          ]
        ]
      }
    ]
  },
  "fishing": {
    "id": "fishing",
    "name": "Fishing",
    "abbr": "FIS",
    "kind": "Gathering Profession",
    "group": "Gathering",
    "sub": "Water gathering",
    "intro": "After you catch a fish you can either sell it to Fred The Fisherman to get fishing experience and gold or ask him to slice it. Sliced Fish can be used in Cooking recipes or it can be sold on market for profit. He is located upstairs, he will either slice fish",
    "meta": [
      {
        "label": "Type",
        "value": "Gathering"
      },
      {
        "label": "Role",
        "value": "Water gathering"
      },
      {
        "label": "Energy",
        "value": "5 energy per catch"
      },
      {
        "label": "Value",
        "value": "Fish, sliced fish, gold, Cooking supply, fishing task progress"
      }
    ],
    "media": "Fishing spot or lure example",
    "chips": [
      "Overview",
      "How to start",
      "Tools",
      "Fish",
      "Daily Task"
    ],
    "notes": [
      {
        "title": "Overview",
        "text": "After you catch a fish you can either sell it to Fred The Fisherman to get fishing experience and gold or ask him to slice it. Sliced Fish can be used in Cooking recipes or it can be sold on market for profit."
      },
      {
        "title": "How to start",
        "text": "1. You get clay fishing rod from lvl 275 reward. If you misplaced it, you can always buy another one from the Tool Merchant at -1 floor in DP building. 2. Around the city there are few spots where you can find fishing spots. They are marked as black circles."
      },
      {
        "title": "Tools",
        "text": "Name Required fishing Ingredients Fishing bonus Clay Fishing Rod 0 Tool Merchant 1000 Gold Coins reward (275 lvl) 3 Iron Fishing Rod 10 100 Iron Ingot 5 Crystal Coins 1 Archlight Token Blacksmith Skill (10) 5 Copper Fishing Rod 20 100 Copper Ingot 25 Crystal Coins 2 Archlight Tok..."
      },
      {
        "title": "Fish",
        "text": "Fish are not exactly bound to fishing rod that you're using. The higher your fishing level is, the bigger fish you will be able to catch. Bigger fish = more experience if you sell it to Fred, more slices if you slice it."
      },
      {
        "title": "Daily Task",
        "text": "To progress faster you can do daily tasks. Each day you will be asked to bring few fishes in exchange for additional fishing experience."
      }
    ],
    "tables": [
      {
        "headers": [
          "Area",
          "Current guide detail"
        ],
        "rows": [
          [
            "Role",
            "Fishing supplies fish and fishing materials for food and Cooking-related crafts."
          ],
          [
            "Rare material",
            "Legendary Fish can appear as a rare fishing result."
          ],
          [
            "Legendary Fish use",
            "Legendary Fish gives much more profession experience and is required for a special meal at the Cooking Station."
          ],
          [
            "Rare requirement",
            "Rare profession materials require profession level 40 and the Dragon Tool for the related profession."
          ],
          [
            "Rare material rate",
            "Later Legacy notes doubled the drop rate of Legendary Fish along with Saffron, Cinnabar Leather, and Magic Quartz."
          ]
        ]
      }
    ]
  },
  "mining": {
    "id": "mining",
    "name": "Mining",
    "abbr": "MIN",
    "kind": "Gathering Profession",
    "group": "Gathering",
    "sub": "Ore extraction",
    "intro": "Ores and ingots are used in many recipes in Blacksmithing , Alchemy , Woodworking and Jewelcrafting . High versatility makes them a high-demand product and mining can be a good source of income.",
    "meta": [
      {
        "label": "Type",
        "value": "Gathering"
      },
      {
        "label": "Role",
        "value": "Ore extraction"
      },
      {
        "label": "Energy",
        "value": "10 energy per successful mine"
      },
      {
        "label": "Value",
        "value": "Ores, ingots, crafting materials, Gold Drop bonus"
      }
    ],
    "media": "Mining vein or tool example",
    "chips": [
      "Overview",
      "How to start",
      "Daily Task",
      "Stat Bonus",
      "Tools",
      "Locations"
    ],
    "notes": [
      {
        "title": "Overview",
        "text": "Ores and ingots are used in many recipes in Blacksmithing , Alchemy , Woodworking and Jewelcrafting . High versatility makes them a high-demand product and mining can be a good source of income."
      },
      {
        "title": "How to start",
        "text": "1. You get clay pickaxe from lvl 275 reward. If you misplaced it, you can always buy another one from the Tool Merchant at -1 floor in DP building. 2. Check out where to find ores and prepare some energy for mining. 3."
      },
      {
        "title": "Daily Task",
        "text": "To progress faster you can do daily tasks. Each day you will be asked to mining specific nodes. They will yield 200% of regular experience."
      },
      {
        "title": "Stat Bonus",
        "text": "When you reach certain tresholds with Mining you will get bonus Gold Drop stats. Mining level Bonus 20 +1 40 +2 60 +3 70 +4 80 +5 90 +7 100 +10 110 +15 120 +25 This bonus isn't additive so on level 120 you will have +25 Gold Drop ."
      },
      {
        "title": "Tools",
        "text": "Name Required mining Ingredients Ores you can mine Rewards Clay Pickaxe 0 Tool Merchant 1000 Gold Coins reward (275 lvl) Clay Ore Vein Iron Ore Vein Clay Ore Iron Ore Iron Pickaxe 10 100 Iron Ingot 5 Crystal Coins 1 Archlight Token Blacksmith Skill (10) Copper Ore Vein Copper Ore..."
      }
    ],
    "tables": [
      {
        "headers": [
          "Area",
          "Current guide detail"
        ],
        "rows": [
          [
            "Role",
            "Mining supplies ores and mining materials for Blacksmithing, Jewelcrafting, and other crafting routes."
          ],
          [
            "Rare node",
            "Mining can spawn Celestial Ore Veins as its rare gathering node path."
          ],
          [
            "Magic Quartz",
            "Mining any node has a small chance to obtain Magic Quartz. A later changelog increased the chance to find Magic Quartz by 4x."
          ],
          [
            "Node tiers",
            "Gathering node tiers were removed, so all nodes can appear in all spawns where the gathering type is supported."
          ],
          [
            "Gather success",
            "Gathering no longer has a failure chance that forces repeated clicking. Tools gather successfully on first click."
          ]
        ]
      }
    ]
  },
  "skinning": {
    "id": "skinning",
    "name": "Skinning",
    "abbr": "SKI",
    "kind": "Gathering Profession",
    "group": "Gathering",
    "sub": "Corpse harvesting",
    "intro": "Skin scraps and blood that you get from monsters is used in Tanning and Alchemy . There is very high demand for high-tier blood vials that are used for polishing and shining oils in Alchemy . This means skinning can become a profitable hobby for someone with n",
    "meta": [
      {
        "label": "Type",
        "value": "Gathering"
      },
      {
        "label": "Role",
        "value": "Corpse harvesting"
      },
      {
        "label": "Energy",
        "value": "5 energy per successful skin"
      },
      {
        "label": "Value",
        "value": "Skin scraps, leather materials, blood vials, Loot Rate bonus"
      }
    ],
    "media": "Skinning material example",
    "chips": [
      "Overview",
      "How to start",
      "Daily Task",
      "Stat Bonus",
      "Tools and spawns"
    ],
    "notes": [
      {
        "title": "Overview",
        "text": "Skin scraps and blood that you get from monsters is used in Tanning and Alchemy . There is very high demand for high-tier blood vials that are used for polishing and shining oils in Alchemy . This means skinning can become a profitable hobby for someone with no social life"
      },
      {
        "title": "How to start",
        "text": "1. You get clay skinning knife from lvl 275 reward. If you misplaced it, you can always buy another one from the Tool Merchant at -1 floor in DP building. 2. Prepare some energy for skinning."
      },
      {
        "title": "Daily Task",
        "text": "To progress faster you can do daily tasks. Each day you will be asked to mining specific nodes. They will yield 200% of regular experience."
      },
      {
        "title": "Stat Bonus",
        "text": "When you reach certain tresholds with Skinning you will get bonus Loot Rate stats. Skinning level Bonus 20 +1 40 +2 60 +3 70 +4 80 +5 90 +7 100 +10 110 +15 120 +25 This bonus isn't additive so on level 120 you will have +25 Loot Rate ."
      },
      {
        "title": "Tools and spawns",
        "text": "Name Required skinning Ingredients Monsters to skin Rewards Clay Skinning Knife 0 Tool Merchant 1000 Gold Coins reward (275 lvl) Stampors Dragons Minotaurs Apes Orcs Also: Larvaes, Forest Furys, Trolls..."
      }
    ],
    "tables": [
      {
        "headers": [
          "Area",
          "Current guide detail"
        ],
        "rows": [
          [
            "Role",
            "Skinning supplies leather materials and corpse-harvested resources for Tanning and other crafts."
          ],
          [
            "Rare material",
            "Cinnabar Skin Scrap can drop as a rare result from all monsters."
          ],
          [
            "Cinnabar Leather",
            "Every 2 Cinnabar Skin Scraps can be crafted into 1 Cinnabar Leather at the Tanning Station."
          ],
          [
            "Blood handling",
            "Blood is obtained by crafting a Blood Vial at the Alchemy Station and using it on a monster corpse. It is no longer directly tied to Skinning."
          ],
          [
            "Cinnabar rate",
            "Later notes increased the Cinnabar Skin Scrap chance to match Magic Quartz, and Cinnabar Leather was later added to the Merchant NPC stock for 1,000."
          ]
        ]
      }
    ]
  },
  "woodcutting": {
    "id": "woodcutting",
    "name": "Woodcutting",
    "abbr": "WOO",
    "kind": "Gathering Profession",
    "group": "Gathering",
    "sub": "Timber harvesting",
    "intro": "Woodcutting is required in order to create new furniture and siege weapons via Woodworking .",
    "meta": [
      {
        "label": "Type",
        "value": "Gathering"
      },
      {
        "label": "Role",
        "value": "Timber harvesting"
      },
      {
        "label": "Energy",
        "value": "10 energy per successful cut"
      },
      {
        "label": "Value",
        "value": "Logs, planks, furniture support, Woodworking materials"
      }
    ],
    "media": "Woodcutting tree or log example",
    "chips": [
      "Overview",
      "How to start",
      "Tools",
      "Locations"
    ],
    "notes": [
      {
        "title": "Overview",
        "text": "Woodcutting is required in order to create new furniture and siege weapons via Woodworking ."
      },
      {
        "title": "How to start",
        "text": "1.Buy a clay hatchet from the Tool Merchant at -1 floor in DP building. 2. Check out where to find trees and prepare some energy for logging! To cut trees you either need to use a hatchet on the tree or simply right-click it with hatchet in any of your backpacks. 3."
      },
      {
        "title": "Tools",
        "text": "Name Required woodcutting Ingredients Trees you can cut Rewards Clay Hatchet 0 Tool Merchant 1 000 Gold Coins Elder Tree Venom Tree Elder Log Venom Log Iron Hatchet 10 100 Iron Ingot 5 Crystal Coins 1 Archlight Token Blacksmith Skill (10) Shadow Tree Shadow Log Copper Hatchet 20..."
      },
      {
        "title": "Locations",
        "text": "Higher tiers of trees can be found in higher tier spawns. High level spawns do not have low-level trees (Elder/Venom). 1. Elder and Venom trees are common in low level areas like: Giant Spiders, Bog Raiders, Werewolves 2."
      }
    ],
    "tables": [
      {
        "headers": [
          "Area",
          "Current guide detail"
        ],
        "rows": [
          [
            "Role",
            "Woodcutting supplies logs and planks for Woodworking and other crafting paths."
          ],
          [
            "Rare node",
            "Woodcutting can spawn Enchanted Trees as its rare gathering node path."
          ],
          [
            "Enchanted Planks",
            "Every 10 Enchanted Logs can craft 5 Enchanted Planks at the Woodworking Station."
          ],
          [
            "Node behavior",
            "Profession nodes no longer disappear with time. A new node may spawn only after one is harvested, with later notes also adding timed resets."
          ],
          [
            "Added areas",
            "Woodcutting nodes were added to Hideout Shores, Nomads, Giant Spiders, Radiant Raider, Gargantoise, Guskos, and Venomed Widow."
          ]
        ]
      }
    ]
  },
  "alchemy": {
    "id": "alchemy",
    "name": "Alchemy",
    "abbr": "ALC",
    "kind": "Crafting Profession",
    "group": "Crafting",
    "sub": "Elixirs, oils, enchantment work",
    "intro": "Alchemy is used to craft various elixirs and oils with bloods that you accumulated from Skinning . Powerful elixirs are not the only reward from this craft, highly skilled alchemists will wield the power of combining Enchantments into their Empowered and Awake",
    "meta": [
      {
        "label": "Type",
        "value": "Crafting"
      },
      {
        "label": "Role",
        "value": "Elixirs, oils, enchantment work"
      },
      {
        "label": "Energy",
        "value": "Recipe-based crafting energy"
      },
      {
        "label": "Value",
        "value": "Elixirs, oils, infusions, enchantment support, Healing and Mana bonuses"
      }
    ],
    "media": "Alchemy station or recipe example",
    "chips": [
      "Overview",
      "How to start",
      "Daily task",
      "Enhancements",
      "Stat Bonus",
      "Crafting Recipes",
      "Rune Exchange"
    ],
    "notes": [
      {
        "title": "Overview",
        "text": "Alchemy is used to craft various elixirs and oils with bloods that you accumulated from Skinning . Powerful elixirs are not the only reward from this craft, highly skilled alchemists will wield the power of combining Enchantments into their Empowered and Awakened forms."
      },
      {
        "title": "How to start",
        "text": "1. When you get your first bloods from Skinning (and few ores from Mining for vials) you should head to -1 floor in DP building, to Daily Alchemy npc. To begin crafting, simply right-click the bellow and select the item you need."
      },
      {
        "title": "Daily task",
        "text": "Once a day you can visit Daily Alchemy npc and ask him for a task. He will ask you to craft something for him, and depending on your level it might be anything from small elixirs to powerful elixir infusions."
      },
      {
        "title": "Enhancements",
        "text": "Enhancement for Alchemy is increasing your Healing . Once you reach certain thresholds new crafting option called Enhancements will appear available. Only then you will be able to pay and obtain your precious title."
      },
      {
        "title": "Stat Bonus",
        "text": "When you reach certain tresholds with alchemy you will get bonus Mana stats. Unlike Enhancements, bonuses are applied automatically once you reach required level."
      }
    ],
    "tables": [
      {
        "headers": [
          "Area",
          "Current guide detail"
        ],
        "rows": [
          [
            "Specialization",
            "Alchemy specializes as Enchanter."
          ],
          [
            "Specialization output",
            "Enchanter unlocks Ascended Enchantment, including Tier 4 enchantment work."
          ],
          [
            "Craft bonus",
            "Alchemy specialization improves elixir bonuses and oil rolling outcomes, including better oil success and higher shining oil values."
          ],
          [
            "Profession elixirs",
            "Profession Elixirs unlock at level 26 and increase profession experience received by 15% for 20 minutes."
          ],
          [
            "Profession Bonus Scroll",
            "Profession Bonus Scroll is listed as a level 46 Alchemy craft with 200 energy to craft."
          ]
        ]
      }
    ]
  },
  "blacksmithing": {
    "id": "blacksmithing",
    "name": "Blacksmithing",
    "abbr": "BLA",
    "kind": "Crafting Profession",
    "group": "Crafting",
    "sub": "Tools, ingots, gear",
    "intro": "Blacksmithing is used to craft various tools, gear and ingots from ores that you get through Mining . Each crafting profession of archlight will Enhance your character in a certain way when you reach higher level. Additionaly to Enhancement, you will get Stat",
    "meta": [
      {
        "label": "Type",
        "value": "Crafting"
      },
      {
        "label": "Role",
        "value": "Tools, ingots, gear"
      },
      {
        "label": "Energy",
        "value": "Recipe-based crafting energy"
      },
      {
        "label": "Value",
        "value": "Ingots, tools, equipment, Damage and Health bonuses"
      }
    ],
    "media": "Forge or ingot crafting example",
    "chips": [
      "Overview",
      "How to start",
      "Daily task",
      "Enhancements",
      "Stat Bonus",
      "Crafting Recipes",
      "Weapon Exchange"
    ],
    "notes": [
      {
        "title": "Overview",
        "text": "Blacksmithing is used to craft various tools, gear and ingots from ores that you get through Mining . Each crafting profession of archlight will Enhance your character in a certain way when you reach higher level."
      },
      {
        "title": "How to start",
        "text": "1. When you get your first ores from Mining you should head to -1 floor in DP building, to Daily Blacksmithing npc. To begin crafting, simply right-click the anvil and select the item you need."
      },
      {
        "title": "Daily task",
        "text": "Once a day you can visit Daily Blacksmithing npc and ask him for a task. He will ask you to craft something for him, and depending on your level it might be anything from clay ingots To mythril tools and gear."
      },
      {
        "title": "Enhancements",
        "text": "Enhancement for Blacksmithing is increasing your overall damage . Once you reach certain thresholds new crafting option called Enhancements will appear available. Only then you will be able to pay and obtain your precious title."
      },
      {
        "title": "Stat Bonus",
        "text": "When you reach certain tresholds with blacksmithing you will get bonus Health stats. Unlike Enhancements, bonuses are applied automatically once you reach required level."
      }
    ],
    "tables": [
      {
        "headers": [
          "Area",
          "Current guide detail"
        ],
        "rows": [
          [
            "Specialization",
            "Blacksmithing specializes as Forge Lord."
          ],
          [
            "Specialization output",
            "Forge Lord covers Stone Transmutation and Honing Stones."
          ],
          [
            "Craft bonus",
            "Blacksmithing specialization improves Honing Stone bonuses and equipment percentages."
          ],
          [
            "Tool crafting",
            "Blacksmithing is the source for tool progression materials. Iron Rod is used for Copper, Steel, Gold, and Mythril tools, while Mythril Rod is used for Dragon tools."
          ],
          [
            "Keys",
            "Cloud Regrade Key and Bone Regrade Key have 100% success and are obtained through Blacksmithing. A later changelog added Legendary Key craft to the Blacksmithing station under Keys."
          ]
        ]
      }
    ]
  },
  "cooking": {
    "id": "cooking",
    "name": "Cooking",
    "abbr": "COO",
    "kind": "Crafting Profession",
    "group": "Crafting",
    "sub": "Meals and buff food",
    "intro": "Cooking gives you the ability to prepare unique dishes of Archlight which will significantly boost your stats and HP/MP regen. To get started, you will need some ingredients. You will have to either buy a farm and start Farming or buy meats and veggies from ot",
    "meta": [
      {
        "label": "Type",
        "value": "Crafting"
      },
      {
        "label": "Role",
        "value": "Meals and buff food"
      },
      {
        "label": "Energy",
        "value": "Recipe-based crafting energy"
      },
      {
        "label": "Value",
        "value": "Prepared meals, stat buffs, regeneration, Healing Received bonus"
      }
    ],
    "media": "Cooking cauldron or meal recipe",
    "chips": [
      "Overview",
      "How to start",
      "Daily task",
      "Enhancements",
      "Stat Bonus",
      "Crafting Recipes"
    ],
    "notes": [
      {
        "title": "Overview",
        "text": "Cooking gives you the ability to prepare unique dishes of Archlight which will significantly boost your stats and HP/MP regen. To get started, you will need some ingredients. You will have to either buy a farm and start Farming or buy meats and veggies from other players."
      },
      {
        "title": "How to start",
        "text": "1. When you get your first veggies from Farming (as well as some fish slices from Fishing ) you should head to -1 floor in DP building, to Horse npc and travel to Farm Shops . To begin crafting, simply right-click the large cauldron and select the meal you need."
      },
      {
        "title": "Daily task",
        "text": "Once a day you can visit Daily Cooking npc and ask him for a task. He will ask you to cook something for him. Every item that is currently needed for your daily task will be marked with question mark next to it's name."
      },
      {
        "title": "Enhancements",
        "text": "Enhancement for Cooking is increasing your Food buff duration . Once you reach certain thresholds new crafting option called Enhancements will appear available. Only then you will be able to pay and obtain your precious title."
      },
      {
        "title": "Stat Bonus",
        "text": "When you reach certain tresholds with cooking you will get bonus Healing Received stats. Unlike Enhancements, bonuses are applied automatically once you reach required level."
      }
    ],
    "tables": [
      {
        "headers": [
          "Area",
          "Current guide detail"
        ],
        "rows": [
          [
            "Specialization",
            "Cooking specializes as Chef."
          ],
          [
            "Specialization output",
            "Chef unlocks Stamina Brew and Legendary Food."
          ],
          [
            "Craft bonus",
            "Cooking specialization improves crafted food bonus percentages."
          ],
          [
            "Advanced ingredients",
            "Advanced Cooking crafts can use Saffron and Legendary Fish."
          ],
          [
            "Recipe fix",
            "A later changelog fixed the Rice Ball recipe using the incorrect item id."
          ]
        ]
      }
    ]
  },
  "jewelcrafting": {
    "id": "jewelcrafting",
    "name": "Jewelcrafting",
    "abbr": "JEW",
    "kind": "Crafting Profession",
    "group": "Crafting",
    "sub": "Gems and jewelry",
    "intro": "Jewelcrafting is used to craft various gems, jewelery and more from ores, leathers, planks and blood vials that you get through Gathering Professions . Each crafting profession of archlight will Enhance your character in a certain way when you reach higher lev",
    "meta": [
      {
        "label": "Type",
        "value": "Crafting"
      },
      {
        "label": "Role",
        "value": "Gems and jewelry"
      },
      {
        "label": "Energy",
        "value": "Recipe-based crafting energy"
      },
      {
        "label": "Value",
        "value": "Gems, jewelry, amulets, Gem and Rune Effectiveness bonuses"
      }
    ],
    "media": "Gem or jewelry crafting example",
    "chips": [
      "Overview",
      "How to start",
      "Daily task",
      "Enhancements",
      "Stat Bonus",
      "Crafting Recipes"
    ],
    "notes": [
      {
        "title": "Overview",
        "text": "Jewelcrafting is used to craft various gems, jewelery and more from ores, leathers, planks and blood vials that you get through Gathering Professions . Each crafting profession of archlight will Enhance your character in a certain way when you reach higher level."
      },
      {
        "title": "How to start",
        "text": "1. When you get your first ores from Mining you should head to -1 floor in DP building, to Daily Jewelcrafting npc. To begin crafting, simply right-click the bellow and select the item you need."
      },
      {
        "title": "Daily task",
        "text": "Once a day you can visit Daily Jewelcrafting npc and ask him for a task. He will ask you to craft something for him, and depending on your level it might be anything from regular gems To charged and overcharged gems."
      },
      {
        "title": "Enhancements",
        "text": "Enhancement for Jewelcrafting is increasing your Gem Effectiveness . Once you reach certain thresholds new crafting option called Enhancements will appear available. Only then you will be able to pay and obtain your precious title."
      },
      {
        "title": "Stat Bonus",
        "text": "When you reach certain tresholds with jewelcrafting you will get bonus Rune Effectiveness stats. Unlike Enhancements, bonuses are applied automatically once you reach required level."
      }
    ],
    "tables": [
      {
        "headers": [
          "Area",
          "Current guide detail"
        ],
        "rows": [
          [
            "Specialization",
            "Jewelcrafting specializes as Gem Cutter."
          ],
          [
            "Specialization output",
            "Gem Cutter unlocks Jewel Sockets and Jewel Frames."
          ],
          [
            "Craft bonus",
            "Jewelcrafting specialization improves Gems, Jewelry, and Jewels."
          ],
          [
            "Gem crafting",
            "Surging Gems use their own crafts and require an Overcharged Gem as an ingredient."
          ],
          [
            "Gem Mixer",
            "Gem Mixer was added as a Jewelcrafting specialization recipe. Later notes increased its gold cost from 5kk to 15kk."
          ]
        ]
      }
    ]
  },
  "tanning": {
    "id": "tanning",
    "name": "Tanning",
    "abbr": "TAN",
    "kind": "Crafting Profession",
    "group": "Crafting",
    "sub": "Leathers, backpacks, decorations",
    "intro": "Tanning is used to craft Backpacks, Beds, Dolls, House Decorations and various other items from leathers that you get through Skinning . Each crafting profession of archlight will Enhance your character in a certain way when you reach higher level. Additionaly",
    "meta": [
      {
        "label": "Type",
        "value": "Crafting"
      },
      {
        "label": "Role",
        "value": "Leathers, backpacks, decorations"
      },
      {
        "label": "Energy",
        "value": "Recipe-based crafting energy"
      },
      {
        "label": "Value",
        "value": "Backpacks, beds, dolls, decorations, Movement Speed and Attack Speed bonuses"
      }
    ],
    "media": "Tanning station or leather output",
    "chips": [
      "Overview",
      "How to start",
      "Daily task",
      "Enhancements",
      "Stat Bonus",
      "Crafting Recipes"
    ],
    "notes": [
      {
        "title": "Overview",
        "text": "Tanning is used to craft Backpacks, Beds, Dolls, House Decorations and various other items from leathers that you get through Skinning . Each crafting profession of archlight will Enhance your character in a certain way when you reach higher level."
      },
      {
        "title": "How to start",
        "text": "1. When you get your first leather scraps from Skinning you should head to -1 floor in DP building, to Daily Tanning npc. To begin crafting, simply right-click the tanning station and select the item you need."
      },
      {
        "title": "Daily task",
        "text": "Once a day you can visit Daily Tanning npc and ask him for a task. He will ask you to craft something for him, and depending on your level it might be few glowing or mythril leathers."
      },
      {
        "title": "Enhancements",
        "text": "Enhancement from Tanning is increasing your movement speed . Once you reach certain thresholds new crafting option called Enhancements will appear available. Only then you will be able to pay and obtain your precious title."
      },
      {
        "title": "Stat Bonus",
        "text": "When you reach certain tresholds with tanning you will get bonus Attack Speed stats. Unlike Enhancements, bonuses are applied automatically once you reach required level."
      }
    ],
    "tables": [
      {
        "headers": [
          "Area",
          "Current guide detail"
        ],
        "rows": [
          [
            "Specialization",
            "Tanning specializes as Tanner Artisan."
          ],
          [
            "Specialization output",
            "Tanner Artisan unlocks a Polishing Coat that allows rarity Oils to be used on weapons."
          ],
          [
            "Craft bonus",
            "Tanning specialization improves Backpacks and Dolls, and improves the chance of getting more stats from Polishing Coat."
          ],
          [
            "Cinnabar Leather",
            "Cinnabar Leather is tied to Cinnabar Skin Scraps and Tanning recipes."
          ],
          [
            "Recipe adjustments",
            "Later notes removed Cinnabar Leathers from Backpacks and Dolls, and reduced Cinnabar Leather requirements for Polishing Coat and Oil Augment."
          ]
        ]
      }
    ]
  },
  "woodworking": {
    "id": "woodworking",
    "name": "Woodworking",
    "abbr": "WOO",
    "kind": "Crafting Profession",
    "group": "Crafting",
    "sub": "Furniture, planks, siege support",
    "intro": "Woodworking is used to craft siege weapons that will help you crush your enemies during Guild Sieges , furnitures and decorations to decorate your house and boost your stats and finally planks, that are used in woodworking and other Crafting Professions . Each",
    "meta": [
      {
        "label": "Type",
        "value": "Crafting"
      },
      {
        "label": "Role",
        "value": "Furniture, planks, siege support"
      },
      {
        "label": "Energy",
        "value": "Recipe-based crafting energy"
      },
      {
        "label": "Value",
        "value": "Planks, furniture, decorations, siege support, Cooldown Reduction bonus"
      }
    ],
    "media": "Woodworking bench or siege craft",
    "chips": [
      "Overview",
      "How to start",
      "Daily task",
      "Enhancements",
      "Stat Bonus",
      "Crafting Recipes"
    ],
    "notes": [
      {
        "title": "Overview",
        "text": "Woodworking is used to craft siege weapons that will help you crush your enemies during Guild Sieges , furnitures and decorations to decorate your house and boost your stats and finally planks, that are used in woodworking and other Crafting Professions ."
      },
      {
        "title": "How to start",
        "text": "1. When you get your first logs from Woodcutting you should head to -1 floor in DP building, to Daily Woodworking npc. To begin crafting, simply right-click the saw and select the item you need."
      },
      {
        "title": "Daily task",
        "text": "Once a day you can visit Daily Woodworking npc and ask him for a task. He will ask you to craft something for him, and depending on your level it might be anything from elder to soul planks."
      },
      {
        "title": "Enhancements",
        "text": "Enhancement for Woodworking is increasing your attack spell cooldown reduction . Once you reach certain thresholds new crafting option called Enhancements will appear available. Only then you will be able to pay and obtain your precious title."
      },
      {
        "title": "Stat Bonus",
        "text": "When you reach certain tresholds with woodworking you will get bonus Cooldown Reduction stats. Unlike Enhancements, bonuses are applied automatically once you reach required level."
      }
    ],
    "tables": [
      {
        "headers": [
          "Area",
          "Current guide detail"
        ],
        "rows": [
          [
            "Specialization",
            "Woodworking specializes as Carpenter."
          ],
          [
            "Specialization output",
            "Carpenter unlocks new furniture and trinkets."
          ],
          [
            "Craft bonus",
            "Woodworking specialization improves Furniture bonuses and increases energy on Beds."
          ],
          [
            "Enchanted Planks",
            "Enchanted Logs from Woodcutting can be converted into Enchanted Planks at the Woodworking Station."
          ],
          [
            "Craft adjustments",
            "Dark Stone Totem received cost and bonus adjustments. Holy Beacon, Chest of Abundance, and Stuffed Bear Display bonuses were adjusted to also increase Monster Essence rate."
          ]
        ]
      }
    ]
  }
};
